.. highlight:: bash
.. |git_url| replace:: https://github.com/borgbackup/borg-import.git
.. _github: https://github.com/borgbackup/borg-import
.. _issue tracker: https://github.com/borgbackup/borg-import/issues
.. _`Python 3`: https://www.python.org/
.. _`pip`: https://pip.pypa.io/en/stable/
.. _virtualenv: https://pypi.python.org/pypi/virtualenv/
.. _`Back In Time`: https://github.com/bit-team/backintime
